In [1]:
# Import dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Load data
tinder_data_to_load = "Resources/Tinder_Millennial_Dataset.csv"

In [4]:
# Read csv
tinder_data = pd.read_csv(tinder_data_to_load)
pd.set_option('max_rows',None)
tinder_data

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
0,292881,Mobile,Mobile respondents,Yes,797,0.207,Yes
1,292883,Mobile,Mobile respondents,No,1969,0.511,No
2,292885,Mobile,Mobile respondents,I don't use Tinder,1090,0.283,Yes
3,292887,Web,Web-based respondents,Yes,0,0.000,No
4,292889,Web,Web-based respondents,No,0,0.000,No
5,292891,Web,Web-based respondents,I don't use Tinder,0,0.000,No
6,292893,Gender,Male respondents,Yes,472,0.213,Yes
7,292895,Gender,Male respondents,No,1172,0.528,No
8,292897,Gender,Male respondents,I don't use Tinder,574,0.259,No
9,292899,Gender,Female respondents,Yes,325,0.198,No
10,292901,Gender,Female respondents,No,797,0.487,Yes
11,292903,Gender,Female respondents,I don't use Tinder,516,0.315,No
12,292905,University,Chapman University,Yes,13,0.206,No
13,292907,University,Chapman University,No,31,0.492,No
14,292909,University,Chapman University,I don't use Tinder,19,0.302,Yes
15,292911,University,Cornell University,Yes,47,0.244,No
16,292913,University,Cornell University,No,95,0.492,Yes
17,292915,University,Cornell University,I don't use Tinder,51,0.264,No
18,292917,University,Duke University,Yes,0,0.000,No
19,292919,University,Duke University,No,2,0.667,No
20,292921,University,Duke University,I don't use Tinder,1,0.333,Yes
21,292923,University,George Washington University,Yes,1,0.250,No
22,292925,University,George Washington University,No,3,0.750,No
23,292927,University,George Washington University,I don't use Tinder,0,0.000,No
24,292929,University,Georgetown University,Yes,2,0.500,Yes
25,292931,University,Georgetown University,No,1,0.250,No
26,292933,University,Georgetown University,I don't use Tinder,1,0.250,No
27,292935,University,Harvard University,Yes,1,0.333,No
28,292937,University,Harvard University,No,2,0.667,Yes
29,292939,University,Harvard University,I don't use Tinder,0,0.000,No
30,292941,University,Indiana University,Yes,9,0.205,Yes
31,292943,University,Indiana University,No,30,0.682,No
32,292945,University,Indiana University,I don't use Tinder,5,0.114,No
33,292947,University,Johns Hopkins University,Yes,33,0.239,No
34,292949,University,Johns Hopkins University,No,76,0.551,Yes
35,292951,University,Johns Hopkins University,I don't use Tinder,29,0.210,No
36,292953,University,Northwestern University,Yes,31,0.258,No
37,292955,University,Northwestern University,No,65,0.542,No
38,292957,University,Northwestern University,I don't use Tinder,24,0.200,Yes
39,292959,University,Ohio State University,Yes,6,0.316,No
40,292961,University,Ohio State University,No,12,0.632,No
41,292963,University,Ohio State University,I don't use Tinder,1,0.053,No
42,292965,University,Princeton University,Yes,1,0.500,Yes
43,292967,University,Princeton University,No,1,0.500,No
44,292969,University,Princeton University,I don't use Tinder,0,0.000,Yes
45,292971,University,San Diego State University,Yes,5,0.192,No
46,292973,University,San Diego State University,No,15,0.577,No
47,292975,University,San Diego State University,I don't use Tinder,6,0.231,No
48,292977,University,Santa Clara University,Yes,0,0.000,Yes
49,292979,University,Santa Clara University,No,4,0.800,No
50,292981,University,Santa Clara University,I don't use Tinder,1,0.200,No
51,292983,University,Southern Methodist University,Yes,3,0.333,No
52,292985,University,Southern Methodist University,No,4,0.444,Yes
53,292987,University,Southern Methodist University,I don't use Tinder,2,0.222,No
54,292989,University,Stanford University,Yes,13,0.120,No
55,292991,University,Stanford University,No,58,0.537,No
56,292993,University,Stanford University,I don't use Tinder,37,0.343,Yes
57,292995,University,Tulane University,Yes,3,0.429,No
58,292997,University,Tulane University,No,3,0.429,Yes
59,292999,University,Tulane University,I don't use Tinder,1,0.143,No
60,293001,University,University of Pennsylvania,Yes,24,0.222,No
61,293003,University,University of Pennsylvania,No,60,0.556,No
62,293005,University,University of Pennsylvania,I don't use Tinder,24,0.222,Yes
63,293007,University,University of Wisconsin-Madison,Yes,34,0.270,No
64,293009,University,University of Wisconsin-Madison,No,71,0.563,No
65,293011,University,University of Wisconsin-Madison,I don't use Tinder,21,0.167,No
66,293013,University,University of Alabama,Yes,2,0.133,Yes
67,293015,University,University of Alabama,No,11,0.733,No
68,293017,University,University of Alabama,I don't use Tinder,2,0.133,No
69,293019,University,"University of California, Berkeley",Yes,25,0.275,No
70,293021,University,"University of California, Berkeley",No,47,0.516,Yes
71,293023,University,"University of California, Berkeley",I don't use Tinder,19,0.209,No
72,293025,University,"University of California, Davis",Yes,3,0.176,Yes
73,293027,University,"University of California, Davis",No,8,0.471,No
74,293029,University,"University of California, Davis",I don't use Tinder,6,0.353,No
75,293031,University,"University of California, Los Angeles",Yes,1,0.077,No
76,293033,University,"University of California, Los Angeles",No,7,0.538,Yes
77,293035,University,"University of California, Los Angeles",I don't use Tinder,5,0.385,No
78,293037,University,"University of California, Santa Barbara",Yes,24,0.320,No
79,293039,University,"University of California, Santa Barbara",No,34,0.453,No
80,293041,University,"University of California, Santa Barbara",I don't use Tinder,17,0.227,Yes
81,293043,University,University of Colorado Boulder,Yes,3,0.500,No
82,293045,University,University of Colorado Boulder,No,3,0.500,No
83,293047,University,University of Colorado Boulder,I don't use Tinder,0,0.000,No
84,293049,University,University of Miami,Yes,0,0.000,Yes
85,293051,University,University of Miami,No,0,0.000,No
86,293053,University,University of Miami,I don't use Tinder,1,1.000,Yes
87,293055,University,University of Michigan,Yes,14,0.163,No
88,293057,University,University of Michigan,No,49,0.570,No
89,293059,University,University of Michigan,I don't use Tinder,23,0.267,No
90,293061,University,University of Oregon,Yes,1,0.200,Yes
91,293063,University,University of Oregon,No,4,0.800,No
92,293065,University,University of Oregon,I don't use Tinder,0,0.000,No
93,293067,University,University of Southern California,Yes,1,0.100,No
94,293069,University,University of Southern California,No,7,0.700,Yes
95,293071,University,University of Southern California,I don't use Tinder,2,0.200,No
96,293073,University,University of Virginia,Yes,3,0.167,No
97,293075,University,University of Virginia,No,7,0.389,No
98,293077,University,University of Virginia,I don't use Tinder,8,0.444,Yes
99,293079,University,Vanderbilt University,Yes,23,0.235,No
100,293081,University,Vanderbilt University,No,63,0.643,Yes
101,293083,University,Vanderbilt University,I don't use Tinder,12,0.122,No
102,293085,University,Wesleyan University,Yes,0,0.000,No
103,293087,University,Wesleyan University,No,2,1.000,No
104,293089,University,Wesleyan University,I don't use Tinder,0,0.000,Yes
105,293091,University,University of Texas,Yes,12,0.164,No
106,293093,University,University of Texas,No,35,0.479,No
107,293095,University,University of Texas,I don't use Tinder,26,0.356,No
108,293097,University,"University of California, San Diego",Yes,1,1.000,Yes
109,293099,University,"University of California, San Diego",No,0,0.000,No
110,293101,University,"University of California, San Diego",I don't use Tinder,0,0.000,No
111,293103,University,Miami University (Ohio),Yes,0,0.000,No
112,293105,University,Miami University (Ohio),No,1,0.500,Yes
113,293107,University,Miami University (Ohio),I don't use Tinder,1,0.500,No
114,293109,University,University of Maine,Yes,0,0.000,Yes
115,293111,University,University of Maine,No,3,0.750,No
116,293113,University,University of Maine,I don't use Tinder,1,0.250,No
117,293115,University,Texas Tech University,Yes,3,0.231,No
118,293117,University,Texas Tech University,No,5,0.385,Yes
119,293119,University,Texas Tech University,I don't use Tinder,5,0.385,No
120,293121,University,University of North Carolina,Yes,1,0.083,No
121,293123,University,University of North Carolina,No,8,0.667,No
122,293125,University,University of North Carolina,I don't use Tinder,3,0.250,Yes
123,293127,University,University of Arkansas,Yes,12,0.182,No
124,293129,University,University of Arkansas,No,35,0.530,No
125,293131,University,University of Arkansas,I don't use Tinder,19,0.288,No
126,293133,University,University of Mississippi,Yes,2,0.667,Yes
127,293135,University,University of Mississippi,No,1,0.333,No
128,293137,University,University of Mississippi,I don't use Tinder,0,0.000,Yes
129,293139,University,Baylor University,Yes,2,0.286,No
130,293141,University,Baylor University,No,2,0.286,No
131,293143,University,Baylor University,I don't use Tinder,3,0.429,No
132,293145,University,Texas A&M University,Yes,13,0.241,Yes
133,293147,University,Texas A&M University,No,29,0.537,No
134,293149,University,Texas A&M University,I don't use Tinder,12,0.222,No
135,293151,University,University of Oklahoma,Yes,0,0.000,No
136,293153,University,University of Oklahoma,No,4,0.800,Yes
137,293155,University,University of Oklahoma,I don't use Tinder,1,0.200,No
138,293157,University,Yale University,Yes,1,1.000,No
139,293159,University,Yale University,No,0,0.000,No
140,293161,University,Yale University,I don't use Tinder,0,0.000,Yes
141,293163,University,Cal Poly San Luis Obispo,Yes,8,0.320,No
142,293165,University,Cal Poly San Luis Obispo,No,10,0.400,Yes
143,293167,University,Cal Poly San Luis Obispo,I don't use Tinder,7,0.280,No
144,293169,University,Carnegie Mellon University,Yes,1,0.250,No
145,293171,University,Carnegie Mellon University,No,3,0.750,No
146,293173,University,Carnegie Mellon University,I don't use Tinder,0,0.000,Yes
147,293175,University,Clemson University,Yes,2,0.500,No
148,293177,University,Clemson University,No,0,0.000,No
149,293179,University,Clemson University,I don't use Tinder,2,0.500,No
150,293181,University,University of Denver,Yes,1,1.000,Yes
151,293183,University,University of Denver,No,0,0.000,No
152,293185,University,University of Denver,I don't use Tinder,0,0.000,No
153,293187,University,University of Washington,Yes,0,0.000,No
154,293189,University,University of Washington,No,3,0.750,Yes
155,293191,University,University of Washington,I don't use Tinder,1,0.250,No
156,293193,University,University of Illinois,Yes,10,0.213,Yes
157,293195,University,University of Illinois,No,29,0.617,No
158,293197,University,University of Illinois,I don't use Tinder,8,0.170,No
159,293199,University,New York University,Yes,1,0.333,No
160,293201,University,New York University,No,2,0.667,Yes
161,293203,University,New York University,I don't use Tinder,0,0.000,No
162,293205,University,Butler University,Yes,7,0.103,No
163,293207,University,Butler University,No,44,0.647,No
164,293209,University,Butler University,I don't use Tinder,17,0.250,Yes
165,293211,University,Washington University in St. Louis,Yes,1,0.125,No
166,293213,University,Washington University in St. Louis,No,5,0.625,No
167,293215,University,Washington University in St. Louis,I don't use Tinder,2,0.250,No
168,293217,University,Northern Illinois University,Yes,0,0.000,Yes
169,293219,University,Northern Illinois University,No,1,0.500,No
170,293221,University,Northern Illinois University,I don't use Tinder,1,0.500,Yes
171,293223,University,University of Iowa,Yes,1,0.333,No
172,293225,University,University of Iowa,No,1,0.333,No
173,293227,University,University of Iowa,I don't use Tinder,1,0.333,No
174,293229,University,Dartmouth College,Yes,5,0.500,Yes
175,293231,University,Dartmouth College,No,3,0.300,No
176,293233,University,Dartmouth College,I don't use Tinder,2,0.200,No
177,293235,University,Loyola Marymount University,Yes,0,0.000,No
178,293237,University,Loyola Marymount University,No,1,1.000,Yes
179,293239,University,Loyola Marymount University,I don't use Tinder,0,0.000,No
180,293241,University,Williams College,Yes,0,0.000,No
181,293243,University,Williams College,No,0,0.000,No
182,293245,University,Williams College,I don't use Tinder,1,1.000,Yes
183,293247,University,University of Maryland,Yes,1,1.000,No
184,293249,University,University of Maryland,No,0,0.000,Yes
185,293251,University,University of Maryland,I don't use Tinder,0,0.000,No
186,293253,University,UMass Amherst,Yes,3,0.250,No
187,293255,University,UMass Amherst,No,6,0.500,No
188,293257,University,UMass Amherst,I don't use Tinder,3,0.250,Yes
189,293259,University,University of Arizona,Yes,4,0.364,No
190,293261,University,University of Arizona,No,4,0.364,No
191,293263,University,University of Arizona,I don't use Tinder,3,0.273,No
192,293265,University,Texas Christian University,Yes,8,0.308,Yes
193,293267,University,Texas Christian University,No,8,0.308,No
194,293269,University,Texas Christian University,I don't use Tinder,10,0.385,No
195,293271,University,Emory University,Yes,1,0.200,No
196,293273,University,Emory University,No,3,0.600,Yes
197,293275,University,Emory University,I don't use Tinder,1,0.200,No
198,293277,University,Columbia University,Yes,2,0.333,Yes
199,293279,University,Columbia University,No,3,0.500,No
200,293281,University,Columbia University,I don't use Tinder,1,0.167,No
201,293283,University,Purdue University,Yes,5,0.192,No
202,293285,University,Purdue University,No,13,0.500,Yes
203,293287,University,Purdue University,I don't use Tinder,8,0.308,No
204,293289,University,Tufts University,Yes,3,0.429,No
205,293291,University,Tufts University,No,2,0.286,No
206,293293,University,Tufts University,I don't use Tinder,2,0.286,Yes
207,293295,University,University of Richmond,Yes,2,0.111,No
208,293297,University,University of Richmond,No,9,0.500,No
209,293299,University,University of Richmond,I don't use Tinder,7,0.389,No
210,293301,University,Quinnipiac University,Yes,0,0.000,Yes
211,293303,University,Quinnipiac University,No,2,1.000,No
212,293305,University,Quinnipiac University,I don't use Tinder,0,0.000,Yes
213,293307,University,United States Naval Academy,Yes,0,0.000,No
214,293309,University,United States Naval Academy,No,3,0.429,No
215,293311,University,United States Naval Academy,I don't use Tinder,4,0.571,No
216,293313,University,"University of California, Santa Cruz",Yes,2,0.667,Yes
217,293315,University,"University of California, Santa Cruz",No,1,0.333,No
218,293317,University,"University of California, Santa Cruz",I don't use Tinder,0,0.000,No
219,293319,University,Rice University,Yes,1,0.167,No
220,293321,University,Rice University,No,4,0.667,Yes
221,293323,University,Rice University,I don't use Tinder,1,0.167,No
222,293325,University,Mississippi State University,Yes,4,0.364,No
223,293327,University,Mississippi State University,No,6,0.545,No
224,293329,University,Mississippi State University,I don't use Tinder,1,0.091,Yes
225,293331,University,University of Missouri,Yes,7,0.233,No
226,293333,University,University of Missouri,No,15,0.500,Yes
227,293335,University,University of Missouri,I don't use Tinder,8,0.267,No
228,293337,University,University of Georgia,Yes,1,0.091,No
229,293339,University,University of Georgia,No,9,0.818,No
230,293341,University,University of Georgia,I don't use Tinder,1,0.091,Yes
231,293343,University,Louisiana State University,Yes,2,0.250,No
232,293345,University,Louisiana State University,No,4,0.500,No
233,293347,University,Louisiana State University,I don't use Tinder,2,0.250,No
234,293349,University,Lehigh University,Yes,0,0.000,Yes
235,293351,University,Lehigh University,No,2,0.667,No
236,293353,University,Lehigh University,I don't use Tinder,1,0.333,No
237,293355,University,Northern Arizona University,Yes,1,1.000,No
238,293357,University,Northern Arizona University,No,0,0.000,Yes
239,293359,University,Northern Arizona University,I don't use Tinder,0,0.000,No
240,293361,University,Elon University,Yes,0,0.000,Yes
241,293363,University,Elon University,No,4,0.667,No
242,293365,University,Elon University,I don't use Tinder,2,0.333,No
243,293367,University,Vassar College,Yes,1,0.500,No
244,293369,University,Vassar College,No,1,0.500,Yes
245,293371,University,Vassar College,I don't use Tinder,0,0.000,No
246,293373,University,University of Pittsburgh,Yes,0,0.000,No
247,293375,University,University of Pittsburgh,No,0,0.000,No
248,293377,University,University of Pittsburgh,I don't use Tinder,2,1.000,Yes
249,293379,University,University of Chicago,Yes,2,0.400,No
250,293381,University,University of Chicago,No,1,0.200,No
251,293383,University,University of Chicago,I don't use Tinder,2,0.400,No
252,293385,University,University of Buffalo,Yes,0,0.000,Yes
253,293387,University,University of Buffalo,No,0,0.000,No
254,293389,University,University of Buffalo,I don't use Tinder,1,1.000,Yes
255,293391,University,University of Minnesota,Yes,2,0.500,No
256,293393,University,University of Minnesota,No,1,0.250,No
257,293395,University,University of Minnesota,I don't use Tinder,1,0.250,No
258,293397,University,Colorado State University,Yes,0,0.000,Yes
259,293399,University,Colorado State University,No,3,1.000,No
260,293401,University,Colorado State University,I don't use Tinder,0,0.000,No
261,293403,University,Skidmore College,Yes,0,0.000,No
262,293405,University,Skidmore College,No,1,1.000,Yes
263,293407,University,Skidmore College,I don't use Tinder,0,0.000,No
264,293409,University,Rochester Institute of Technology,Yes,0,0.000,No
265,293411,University,Rochester Institute of Technology,No,2,1.000,No
266,293413,University,Rochester Institute of Technology,I don't use Tinder,0,0.000,Yes
267,293415,University,Arizona State University,Yes,0,0.000,No
268,293417,University,Arizona State University,No,1,0.500,Yes
269,293419,University,Arizona State University,I don't use Tinder,1,0.500,No
270,293421,University,University of Rochester,Yes,1,0.333,No
271,293423,University,University of Rochester,No,2,0.667,No
272,293425,University,University of Rochester,I don't use Tinder,0,0.000,Yes
273,293427,University,University of St Andrews,Yes,0,0.000,No
274,293429,University,University of St Andrews,No,2,0.667,No
275,293431,University,University of St Andrews,I don't use Tinder,1,0.333,No
276,293433,University,Florida State University,Yes,0,0.000,Yes
277,293435,University,Florida State University,No,0,0.000,No
278,293437,University,Florida State University,I don't use Tinder,1,1.000,No
279,293439,University,Ithaca College,Yes,1,0.250,No
280,293441,University,Ithaca College,No,2,0.500,Yes
281,293443,University,Ithaca College,I don't use Tinder,1,0.250,No
282,293445,University,Union College,Yes,1,0.111,Yes
283,293447,University,Union College,No,7,0.778,No
284,293449,University,Union College,I don't use Tinder,1,0.111,No
285,293451,University,Loyola University Maryland,Yes,0,0.000,No
286,293453,University,Loyola University Maryland,No,3,1.000,Yes
287,293455,University,Loyola University Maryland,I don't use Tinder,0,0.000,No
288,293457,University,Marquette University,Yes,1,0.500,No
289,293459,University,Marquette University,No,1,0.500,No
290,293461,University,Marquette University,I don't use Tinder,0,0.000,Yes
291,293463,University,James Madison University,Yes,1,1.000,No
292,293465,University,James Madison University,No,0,0.000,No
293,293467,University,James Madison University,I don't use Tinder,0,0.000,No
294,293469,University,Sacred Heart University,Yes,0,0.000,Yes
295,293471,University,Sacred Heart University,No,1,1.000,No
296,293473,University,Sacred Heart University,I don't use Tinder,0,0.000,Yes
297,293475,University,University of Wisconsin-Whitewater,Yes,2,0.400,No
298,293477,University,University of Wisconsin-Whitewater,No,2,0.400,No
299,293479,University,University of Wisconsin-Whitewater,I don't use Tinder,1,0.200,No
300,293481,University,St. Lawrence University,Yes,1,1.000,Yes
301,293483,University,St. Lawrence University,No,0,0.000,No
302,293485,University,St. Lawrence University,I don't use Tinder,0,0.000,No
303,293487,University,Iowa State University,Yes,0,0.000,No
304,293489,University,Iowa State University,No,1,1.000,Yes

In [5]:
tinder_data.info

<bound method DataFrame.info of          ID Segment Type                      Segment Description  \
0    292881       Mobile                       Mobile respondents
1    292883       Mobile                       Mobile respondents
2    292885       Mobile                       Mobile respondents
3    292887          Web                    Web-based respondents
4    292889          Web                    Web-based respondents
5    292891          Web                    Web-based respondents
6    292893       Gender                         Male respondents
7    292895       Gender                         Male respondents
8    292897       Gender                         Male respondents
9    292899       Gender                       Female respondents
10   292901       Gender                       Female respondents
11   292903       Gender                       Female respondents
12   292905   University                       Chapman University
13   292907   University                       Chapman University
14   292909   University                       Chapman University
15   292911   University                       Cornell University
16   292913   University                       Cornell University
17   292915   University                       Cornell University
18   292917   University                          Duke University
19   292919   University                          Duke University
20   292921   University                          Duke University
21   292923   University             George Washington University
22   292925   University             George Washington University
23   292927   University             George Washington University
24   292929   University                    Georgetown University
25   292931   University                    Georgetown University
26   292933   University                    Georgetown University
27   292935   University                       Harvard University
28   292937   University                       Harvard University
29   292939   University                       Harvard University
30   292941   University                       Indiana University
31   292943   University                       Indiana University
32   292945   University                       Indiana University
33   292947   University                 Johns Hopkins University
34   292949   University                 Johns Hopkins University
35   292951   University                 Johns Hopkins University
36   292953   University                  Northwestern University
37   292955   University                  Northwestern University
38   292957   University                  Northwestern University
39   292959   University                    Ohio State University
40   292961   University                    Ohio State University
41   292963   University                    Ohio State University
42   292965   University                     Princeton University
43   292967   University                     Princeton University
44   292969   University                     Princeton University
45   292971   University               San Diego State University
46   292973   University               San Diego State University
47   292975   University               San Diego State University
48   292977   University                   Santa Clara University
49   292979   University                   Santa Clara University
50   292981   University                   Santa Clara University
51   292983   University            Southern Methodist University
52   292985   University            Southern Methodist University
53   292987   University            Southern Methodist University
54   292989   University                      Stanford University
55   292991   University                      Stanford University
56   292993   University                      Stanford University
57   292995   University                        Tulane University
58   292997   University                        Tulane University
59   292999   University                        Tulane University
60   293001   University               University of Pennsylvania
61   293003   University               University of Pennsylvania
62   293005   University               University of Pennsylvania
63   293007   University          University of Wisconsin-Madison
64   293009   University          University of Wisconsin-Madison
65   293011   University          University of Wisconsin-Madison
66   293013   University                    University of Alabama
67   293015   University                    University of Alabama
68   293017   University                    University of Alabama
69   293019   University       University of California, Berkeley
70   293021   University       University of California, Berkeley
71   293023   University       University of California, Berkeley
72   293025   University          University of California, Davis
73   293027   University          University of California, Davis
74   293029   University          University of California, Davis
75   293031   University    University of California, Los Angeles
76   293033   University    University of California, Los Angeles
77   293035   University    University of California, Los Angeles
78   293037   University  University of California, Santa Barbara
79   293039   University  University of California, Santa Barbara
80   293041   University  University of California, Santa Barbara
81   293043   University           University of Colorado Boulder
82   293045   University           University of Colorado Boulder
83   293047   University           University of Colorado Boulder
84   293049   University                      University of Miami
85   293051   University                      University of Miami
86   293053   University                      University of Miami
87   293055   University                   University of Michigan
88   293057   University                   University of Michigan
89   293059   University                   University of Michigan
90   293061   University                     University of Oregon
91   293063   University                     University of Oregon
92   293065   University                     University of Oregon
93   293067   University        University of Southern California
94   293069   University        University of Southern California
95   293071   University        University of Southern California
96   293073   University                   University of Virginia
97   293075   University                   University of Virginia
98   293077   University                   University of Virginia
99   293079   University                    Vanderbilt University
100  293081   University                    Vanderbilt University
101  293083   University                    Vanderbilt University
102  293085   University                      Wesleyan University
103  293087   University                      Wesleyan University
104  293089   University                      Wesleyan University
105  293091   University                      University of Texas
106  293093   University                      University of Texas
107  293095   University                      University of Texas
108  293097   University      University of California, San Diego
109  293099   University      University of California, San Diego
110  293101   University      University of California, San Diego
111  293103   University                  Miami University (Ohio)
112  293105   University                  Miami University (Ohio)
113  293107   University                  Miami University (Ohio)
114  293109   University                      University of Maine
115  293111   University                      University of Maine
116  293113   University                      University of Maine
117  293115   University                    Texas Tech University
118  293117   University                    Texas Tech University
119  293119   University                    Texas Tech University
120  293121   University             University of North Carolina
121  293123   University             University of North Carolina
122  293125   University             University of North Carolina
123  293127   University                   University of Arkansas
124  293129   University                   University of Arkansas
125  293131   University                   University of Arkansas
126  293133   University                University of Mississippi
127  293135   University                University of Mississippi
128  293137   University                University of Mississippi
129  293139   University                        Baylor University
130  293141   University                        Baylor University
131  293143   University                        Baylor University
132  293145   University                     Texas A&M University
133  293147   University                     Texas A&M University
134  293149   University                     Texas A&M University
135  293151   University                   University of Oklahoma
136  293153   University                   University of Oklahoma
137  293155   University                   University of Oklahoma
138  293157   University                          Yale University
139  293159   University                          Yale University
140  293161   University                          Yale University
141  293163   University                 Cal Poly San Luis Obispo
142  293165   University                 Cal Poly San Luis Obispo
143  293167   University                 Cal Poly San Luis Obispo
144  293169   University               Carnegie Mellon University
145  293171   University               Carnegie Mellon University
146  293173   University               Carnegie Mellon University
147  293175   University                       Clemson University
148  293177   University                       Clemson University
149  293179   University                       Clemson University
150  293181   University                     University of Denver
151  293183   University                     University of Denver
152  293185   University                     University of Denver
153  293187   University                 University of Washington
154  293189   University                 University of Washington
155  293191   University                 University of Washington
156  293193   University                   University of Illinois
157  293195   University                   University of Illinois
158  293197   University                   University of Illinois
159  293199   University                      New York University
160  293201   University                      New York University
161  293203   University                      New York University
162  293205   University                        Butler University
163  293207   University                        Butler University
164  293209   University                        Butler University
165  293211   University       Washington University in St. Louis
166  293213   University       Washington University in St. Louis
167  293215   University       Washington University in St. Louis
168  293217   University             Northern Illinois University
169  293219   University             Northern Illinois University
170  293221   University             Northern Illinois University
171  293223   University                       University of Iowa
172  293225   University                       University of Iowa
173  293227   University                       University of Iowa
174  293229   University                        Dartmouth College
175  293231   University                        Dartmouth College
176  293233   University                        Dartmouth College
177  293235   University              Loyola Marymount University
178  293237   University              Loyola Marymount University
179  293239   University              Loyola Marymount University
180  293241   University                         Williams College
181  293243   University                         Williams College
182  293245   University                         Williams College
183  293247   University                   University of Maryland
184  293249   University                   University of Maryland
185  293251   University                   University of Maryland
186  293253   University                            UMass Amherst
187  293255   University                            UMass Amherst
188  293257   University                            UMass Amherst
189  293259   University                    University of Arizona
190  293261   University                    University of Arizona
191  293263   University                    University of Arizona
192  293265   University               Texas Christian University
193  293267   University               Texas Christian University
194  293269   University               Texas Christian University
195  293271   University                         Emory University
196  293273   University                         Emory University
197  293275   University                         Emory University
198  293277   University                      Columbia University
199  293279   University                      Columbia University
200  293281   University                      Columbia University
201  293283   University                        Purdue University
202  293285   University                        Purdue University
203  293287   University                        Purdue University
204  293289   University                         Tufts University
205  293291   University                         Tufts University
206  293293   University                         Tufts University
207  293295   University                   University of Richmond
208  293297   University                   University of Richmond
209  293299   University                   University of Richmond
210  293301   University                    Quinnipiac University
211  293303   University                    Quinnipiac University
212  293305   University                    Quinnipiac University
213  293307   University              United States Naval Academy
214  293309   University              United States Naval Academy
215  293311   University              United States Naval Academy
216  293313   University     University of California, Santa Cruz
217  293315   University     University of California, Santa Cruz
218  293317   University     University of California, Santa Cruz
219  293319   University                         Rice University
220  293321   University                         Rice University
221  293323   University                         Rice University
222  293325   University             Mississippi State University
223  293327   University             Mississippi State University
224  293329   University             Mississippi State University
225  293331   University                   University of Missouri
226  293333   University                   University of Missouri
227  293335   University                   University of Missouri
228  293337   University                    University of Georgia
229  293339   University                    University of Georgia
230  293341   University                    University of Georgia
231  293343   University               Louisiana State University
232  293345   University               Louisiana State University
233  293347   University               Louisiana State University
234  293349   University                        Lehigh University
235  293351   University                        Lehigh University
236  293353   University                        Lehigh University
237  293355   University              Northern Arizona University
238  293357   University              Northern Arizona University
239  293359   University              Northern Arizona University
240  293361   University                          Elon University
241  293363   University                          Elon University
242  293365   University                          Elon University
243  293367   University                           Vassar College
244  293369   University                           Vassar College
245  293371   University                           Vassar College
246  293373   University                 University of Pittsburgh
247  293375   University                 University of Pittsburgh
248  293377   University                 University of Pittsburgh
249  293379   University                    University of Chicago
250  293381   University                    University of Chicago
251  293383   University                    University of Chicago
252  293385   University                    University of Buffalo
253  293387   University                    University of Buffalo
254  293389   University                    University of Buffalo
255  293391   University                  University of Minnesota
256  293393   University                  University of Minnesota
257  293395   University                  University of Minnesota
258  293397   University                Colorado State University
259  293399   University                Colorado State University
260  293401   University                Colorado State University
261  293403   University                         Skidmore College
262  293405   University                         Skidmore College
263  293407   University                         Skidmore College
264  293409   University        Rochester Institute of Technology
265  293411   University        Rochester Institute of Technology
266  293413   University        Rochester Institute of Technology
267  293415   University                 Arizona State University
268  293417   University                 Arizona State University
269  293419   University                 Arizona State University
270  293421   University                  University of Rochester
271  293423   University                  University of Rochester
272  293425   University                  University of Rochester
273  293427   University                 University of St Andrews
274  293429   University                 University of St Andrews
275  293431   University                 University of St Andrews
276  293433   University                 Florida State University
277  293435   University                 Florida State University
278  293437   University                 Florida State University
279  293439   University                           Ithaca College
280  293441   University                           Ithaca College
281  293443   University                           Ithaca College
282  293445   University                            Union College
283  293447   University                            Union College
284  293449   University                            Union College
285  293451   University               Loyola University Maryland
286  293453   University               Loyola University Maryland
287  293455   University               Loyola University Maryland
288  293457   University                     Marquette University
289  293459   University                     Marquette University
290  293461   University                     Marquette University
291  293463   University                 James Madison University
292  293465   University                 James Madison University
293  293467   University                 James Madison University
294  293469   University                  Sacred Heart University
295  293471   University                  Sacred Heart University
296  293473   University                  Sacred Heart University
297  293475   University       University of Wisconsin-Whitewater
298  293477   University       University of Wisconsin-Whitewater
299  293479   University       University of Wisconsin-Whitewater
300  293481   University                  St. Lawrence University

In [5]:
#tinder_data.info

<bound method DataFrame.info of          ID Segment Type    Segment Description              Answer  Count  \
0    292881       Mobile     Mobile respondents                 Yes    797
1    292883       Mobile     Mobile respondents                  No   1969
2    292885       Mobile     Mobile respondents  I don't use Tinder   1090
3    292887          Web  Web-based respondents                 Yes      0
4    292889          Web  Web-based respondents                  No      0
..      ...          ...                    ...                 ...    ...
448  293777   University         Boston College                  No      4
449  293779   University         Boston College  I don't use Tinder      1
450  293781   University      Boston University                 Yes      2
451  293783   University      Boston University                  No      3
452  293785   University      Boston University  I don't use Tinder      1

     Percentage It became a Relationship
0         0.207                      Yes
1         0.511                       No
2         0.283                      Yes
3         0.000                       No
4         0.000                       No
..          ...                      ...
448       0.800                      Yes
449       0.200                       No
450       0.333                      Yes
451       0.500                       No
452       0.167                       No

[453 rows x 7 columns]>

In [6]:
tinder_data.describe()

                  ID        Count  Percentage
count     453.000000   453.000000  453.000000
mean   293333.000000    22.373068    0.331141
std       261.828188   136.996075    0.316157
min    292881.000000     0.000000    0.000000
25%    293107.000000     0.000000    0.000000
50%    293333.000000     1.000000    0.250000
75%    293559.000000     4.000000    0.500000
max    293785.000000  1969.000000    1.000000

In [7]:
category = ['Segment Type', 'Segment Description', 'Answer', 'It became a Relationship']
for column in category:
    print('Unique values in "{}" column count: {}'.format(column, tinder_data[column].nunique()))
    print(tinder_data[column].unique())
    print()

Unique values in "Segment Type" column count: 4
['Mobile' 'Web' 'Gender' 'University']

Unique values in "Segment Description" column count: 151
['Mobile respondents' 'Web-based respondents' 'Male respondents'
 'Female respondents' 'Chapman University' 'Cornell University'
 'Duke University' 'George Washington University' 'Georgetown University'
 'Harvard University' 'Indiana University' 'Johns Hopkins University'
 'Northwestern University' 'Ohio State University' 'Princeton University'
 'San Diego State University' 'Santa Clara University'
 'Southern Methodist University' 'Stanford University' 'Tulane University'
 'University of Pennsylvania' 'University of Wisconsin-Madison'
 'University of Alabama' 'University of California, Berkeley'
 'University of California, Davis' 'University of California, Los Angeles'
 'University of California, Santa Barbara'
 'University of Colorado Boulder' 'University of Miami'
 'University of Michigan' 'University of Oregon'
 'University of Southern California' 'University of Virginia'
 'Vanderbilt University' 'Wesleyan University' 'University of Texas'
 'University of California, San Diego' 'Miami University (Ohio)'
 'University of Maine' 'Texas Tech University'
 'University of North Carolina' 'University of Arkansas'
 'University of Mississippi' 'Baylor University' 'Texas A&M University'
 'University of Oklahoma' 'Yale University' 'Cal Poly San Luis Obispo'
 'Carnegie Mellon University' 'Clemson University' 'University of Denver'
 'University of Washington' 'University of Illinois' 'New York University'
 'Butler University' 'Washington University in St. Louis'
 'Northern Illinois University' 'University of Iowa' 'Dartmouth College'
 'Loyola Marymount University' 'Williams College' 'University of Maryland'
 'UMass Amherst' 'University of Arizona' 'Texas Christian University'
 'Emory University' 'Columbia University' 'Purdue University'
 'Tufts University' 'University of Richmond' 'Quinnipiac University'
 'United States Naval Academy' 'University of California, Santa Cruz'
 'Rice University ' 'Mississippi State University'
 'University of Missouri' 'University of Georgia'
 'Louisiana State University' 'Lehigh University'
 'Northern Arizona University' 'Elon University' 'Vassar College'
 'University of Pittsburgh' 'University of Chicago'
 'University of Buffalo' 'University of Minnesota'
 'Colorado State University' 'Skidmore College'
 'Rochester Institute of Technology' 'Arizona State University'
 'University of Rochester' 'University of St Andrews'
 'Florida State University' 'Ithaca College' 'Union College'
 'Loyola University Maryland' 'Marquette University'
 'James Madison University' 'Sacred Heart University'
 'University of Wisconsin-Whitewater' 'St. Lawrence University'
 'Iowa State University' 'University of Wisconsin-La Crosse'
 'College of William and Mary' 'University of Notre Dame'
 'University of Tennessee' 'Illinois State' 'Auburn University'
 'Gonzaga University' 'Washington State University'
 'Michigan State University' 'Florida International University'
 'University of Central Florida' 'Castleton State College'
 'Cal State Northridge' 'Ohio University' 'Pepperdine University'
 'Providence College' 'Appalachian State University'
 'University of Connecticut' 'University of Wisconsin, Eau Claire'
 'University of Delaware' 'Massachusetts Institute of Technology'
 'Oregon State University' 'Whatsgoodly University'
 'Case Western Reserve University' 'Michigan Technological University'
 'Meridian, Idaho' 'University of Dayton' 'University of Kansas'
 'Morehead State University' 'University of Central Oklahoma'
 'Syracuse University' 'Colby College' 'Brigham Young University'
 'Arkansas State University' 'Westport, CT' 'Centre College'
 'Middlebury College' 'North Carolina State' 'University of Kentucky'
 'Bucknell University' 'Randolph-Macon College' 'Old Dominion University'
 'University of Tampa' 'Roger Williams University' 'Penn State University'
 'Minnesota State University Mankato' 'University of Florida'
 'Boston College' 'Boston University']

Unique values in "Answer" column count: 3
['Yes' 'No' "I don't use Tinder"]

Unique values in "It became a Relationship" column count: 2
['Yes' 'No']

In [8]:
# Convert answers for 'It became a relationship' column
dictionary = {'Yes':1, 'No':0}

In [9]:
# Only look at data from University of California, Davis
UCD_df = tinder_data[tinder_data["Segment Description"] == "University of California, Davis"]
UCD_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
72,293025,University,"University of California, Davis",Yes,3,0.176,Yes
73,293027,University,"University of California, Davis",No,8,0.471,No
74,293029,University,"University of California, Davis",I don't use Tinder,6,0.353,No

In [10]:
# Only look at data from University of California, Berkeley
UCB_df = tinder_data[tinder_data["Segment Description"] == "University of California, Berkeley"]
UCB_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
69,293019,University,"University of California, Berkeley",Yes,25,0.275,No
70,293021,University,"University of California, Berkeley",No,47,0.516,Yes
71,293023,University,"University of California, Berkeley",I don't use Tinder,19,0.209,No

In [11]:
# Only look at data from Santa Clara University
santa_clara_df = tinder_data[tinder_data["Segment Description"] == "Santa Clara University"]
santa_clara_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
48,292977,University,Santa Clara University,Yes,0,0.0,Yes
49,292979,University,Santa Clara University,No,4,0.8,No
50,292981,University,Santa Clara University,I don't use Tinder,1,0.2,No

In [12]:
# Only look at data from Stanford University
stanford_df = tinder_data[tinder_data["Segment Description"] == "Stanford University"]
stanford_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
54,292989,University,Stanford University,Yes,13,0.120,No
55,292991,University,Stanford University,No,58,0.537,No
56,292993,University,Stanford University,I don't use Tinder,37,0.343,Yes

In [13]:
# Only look at data from University of California, Santa Cruz
UCSC_df = tinder_data[tinder_data["Segment Description"] == "University of California, Santa Cruz"]
UCSC_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
216,293313,University,"University of California, Santa Cruz",Yes,2,0.667,Yes
217,293315,University,"University of California, Santa Cruz",No,1,0.333,No
218,293317,University,"University of California, Santa Cruz",I don't use Tinder,0,0.000,No

In [14]:
# Only look at data from Cal Poly San Luis Obispo
cal_poly_df = tinder_data[tinder_data["Segment Description"] == "Cal Poly San Luis Obispo"]
cal_poly_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
141,293163,University,Cal Poly San Luis Obispo,Yes,8,0.32,No
142,293165,University,Cal Poly San Luis Obispo,No,10,0.40,Yes
143,293167,University,Cal Poly San Luis Obispo,I don't use Tinder,7,0.28,No

In [15]:
# Only look at data from University of California, Santa Barbara
UCSB_df = tinder_data[tinder_data["Segment Description"] == "University of California, Santa Barbara"]
UCSB_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
78,293037,University,"University of California, Santa Barbara",Yes,24,0.320,No
79,293039,University,"University of California, Santa Barbara",No,34,0.453,No
80,293041,University,"University of California, Santa Barbara",I don't use Tinder,17,0.227,Yes

In [16]:
# Only look at data from Cal State Northridge
CSUN_df = tinder_data[tinder_data["Segment Description"] == "Cal State Northridge"]
CSUN_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
342,293565,University,Cal State Northridge,Yes,0,0.000,Yes
343,293567,University,Cal State Northridge,No,2,0.667,No
344,293569,University,Cal State Northridge,I don't use Tinder,1,0.333,No

In [17]:
# Only look at data from University of California, Los Angeles
UCLA_df = tinder_data[tinder_data["Segment Description"] == "University of California, Los Angeles"]
UCLA_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
75,293031,University,"University of California, Los Angeles",Yes,1,0.077,No
76,293033,University,"University of California, Los Angeles",No,7,0.538,Yes
77,293035,University,"University of California, Los Angeles",I don't use Tinder,5,0.385,No

In [18]:
# Only look at data from University of Southern California
USC_df = tinder_data[tinder_data["Segment Description"] == "University of Southern California"]
USC_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
93,293067,University,University of Southern California,Yes,1,0.1,No
94,293069,University,University of Southern California,No,7,0.7,Yes
95,293071,University,University of Southern California,I don't use Tinder,2,0.2,No

In [19]:
# Only look at data from University of California, San Diego
UCSD_df = tinder_data[tinder_data["Segment Description"] == "University of California, San Diego"]
UCSD_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
108,293097,University,"University of California, San Diego",Yes,1,1.0,Yes
109,293099,University,"University of California, San Diego",No,0,0.0,No
110,293101,University,"University of California, San Diego",I don't use Tinder,0,0.0,No

In [20]:
# Only look at data from San Diego State University
SDSU_df = tinder_data[tinder_data["Segment Description"] == "San Diego State University"]
SDSU_df

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
45,292971,University,San Diego State University,Yes,5,0.192,No
46,292973,University,San Diego State University,No,15,0.577,No
47,292975,University,San Diego State University,I don't use Tinder,6,0.231,No

In [21]:
# Boxplot of match count 
plt.figure(figsize=(14,6))
sns.boxplot(x=df['Count'], y=df['It became a Relationship'].astype('category'))
plt.xscale('log')
plt.title('Boxplot of match counts')

NameError: name 'sns' is not defined